version: '3'

services:
  rabbit:
    image: rabbitmq:latest
    container_name: celery_rabbit
    volumes:
      - ./rabbitmq/data/:/var/lib/rabbitmq/

  web:
    build: .
    container_name: celery_backend_rabbit
    command: sh -c "python manage.py runserver 0.0.0.0:8001"
    volumes:
      - .:/usr/src/app
    ports:
      - 8001:8001
    depends_on:
      - rabbit
